------- FILE FORMAT FOR LOADING DATA FROM CSV FILE -------
CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT='DD/MM/YYYY'
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT='YYYY-MM-DD"T"HH24:MI:SS'; 
